import Navigation from "../components/navigation";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* 주석추가 */}
        {/* 주석추가2 */}
        <Navigation />
        {children}
      </body>
    </html>
  )
}
